name: CMake build and test

on:
  workflow_call

jobs:
  #Build Linux and MacOS job
  build-linux-mac:
    name: Build ${{ matrix.name }}
    strategy:
      matrix:
        include:
        - os: ubuntu-latest
          name: Linux
          filepath: build/release/dsa_app/
          filename: dsa_app
          ext: -linux.x86_64
        - os: macos-latest
          name: MacOS
          filepath: build/release/dsa_app/
          filename: dsa_app
          ext: -macos.arm64

    runs-on: ${{ matrix.os }}

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v7
    - name: Configure
      run: cmake --preset release
    - name: Build
      run: cmake --build --preset release --parallel
    - name: Rename MacOS and Linux executable
      run: |
        mv ${{ matrix.filepath }}${{ matrix.filename }} \
        ${{ matrix.filepath }}${{ matrix.filename }}${{ matrix.ext }}
    - name: Upload artifacts
      uses: actions/upload-artifact@v7
      with:
        name: ${{ matrix.name }}
        path: ${{ matrix.filepath }}${{ matrix.filename }}${{ matrix.ext }}

#Build Windows job
  build-windows:
    name: Build Windows
    runs-on: windows-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v7
    - name: Setup MSVC
      uses: TheMrMilchmann/setup-msvc-dev@v4
      with:
        arch: x64
    - name: Configure
      run: cmake --preset release
    - name: Build
      run: cmake --build --preset release --parallel
    - name: Rename Windows executable
      run: |
        ren build/release/dsa_app/dsa_app.exe dsa_app-windows.exe
    - name: Upload artifacts
      uses: actions/upload-artifact@v7
      with:
        name: Windows
        path: build/release/dsa_app/dsa_app-windows.exe